USE AdventureWorks2019
GO

-- Sample Query
SELECT *
FROM [Sales].[SalesPerson]
GO

-- Logical and Physical Mapping and query cost
SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

-- Alternate Plan Generated by Query Hint
SELECT * 
FROM [Sales].[SalesPerson] sp
INNER HASH JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

-- Display Options of Execution Plans - STATISTICS TIME
SET STATISTICS TIME ON
GO
SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

SET STATISTICS TIME OFF
GO

-- Display Options of Execution Plans - STATISTICS IO
SET STATISTICS IO ON
GO

SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

SET STATISTICS IO OFF
GO

-- Display Options of Estimated Execution Plans - Text - SHOWPLAN_TEXT
SET SHOWPLAN_TEXT ON
GO
SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

SET SHOWPLAN_TEXT OFF
GO

-- Display Options of Estimated Execution Plans - Text - SHOWPLAN_ALL
SET SHOWPLAN_ALL ON
GO

SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

SET SHOWPLAN_ALL OFF
GO

-- Display Options of Actual Execution Plans - Text - STATISTICS PROFILE
SET STATISTICS PROFILE ON
GO

SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

SET STATISTICS PROFILE OFF
GO

-- Display Options of Estimated Execution Plans - XML - SHOWPLAN_XML
SET SHOWPLAN_XML ON
GO

SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

SET SHOWPLAN_XML OFF
GO

-- Display Options of Actual Execution Plans - XML - STATISTICS XML
SET STATISTICS XML ON
GO

SELECT * 
FROM [Sales].[SalesPerson] sp
INNER JOIN [Sales].[SalesPersonQuotaHistory] spq
	ON sp.BusinessEntityID = spq.BusinessEntityID
ORDER BY sp.SalesQuota
GO

SET STATISTICS XML OFF
GO